name: Generate README

on:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created, edited]

jobs:
  sync:
    name: Generate README
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: Configure pip cache
        uses: actions/cache@v1
        id: pip-cache
        with:
          path: venv
          key: pip-1-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            pip-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m venv venv
          source venv/bin/activate
          pip install -r tools/requirements.txt
        if: steps.pip-cache.outputs.cache-hit != 'true'

      - name: Generate new md
        run: |
          source venv/bin/activate
          python tools/issue2md.py ${{ secrets.GT }} ${{ github.repository }} ${{ github.event.issue.number }}
        
      - name: Push README
        uses: github-actions-x/commit@v2.6
        with:
          github-token: ${{ secrets.GT }}
          commit-message: "Refresh README"
          files: README.md
          rebase: 'true'
          name: egolearner 
          email: lijiliang@outlook.com
